### PR TITLE
enable using pytest-django

### PR DESCRIPTION
**Pull request by megies**
supersedes and closes #51

### CODE REVIEW

**Comment by krischer** [comment]
How about also using this in the CI?

**Comment by barsch** [comment]
tl;dr: I really like to keep the number of dependencies low (this also applies for ObsPy)

I don't like those new dependencies on ```pytest```, ```django-nose``` and ```django-pytest``` - I learned the hard way that relying on to many thrid-party dependencies will fail in the future as people tend to stop maintaining a project - e.g. ```django-plugins``` ^^

maybe I don't see the point but why do we need this dependencies which is not working with the default installation (bear in mind that you can use for your local environment whatever you want) - does the test suite in CI not work without?

**Comment by krischer** [comment]
Fair enough. I nowadays strongly prefer `pytest` to the normal the built-in unit testing framework as it is just a lot more expressive but I do agree that we don't need the additional dependency right now.

Speaking of `django-plugins`: Do you think we could just replace it with `pkgutils` plug-in system? I really don't want to maintain it long-term to be honest (and its already a couple django versions behind). It just takes a deep dive in django and I don't know it well enough to do it without a lot of effort.

**Comment by barsch** [comment]
> Do you think we could just replace it with pkgutils plug-in system?

I guess so - I would like to remove that - problem is that I'm at the moment very packed with work - so I don't see me this touching in the next weeks ... I could also look into django-plugins an bring it up-to-date ...

**Comment by krischer** [comment]
> I could also look into django-plugins an bring it up-to-date ...

That would also be nice.

If I find some time I can also give replacing `django-plugins` a shot. But updating `django-plugins` would be a nightmare for me.

**Comment by barsch** [comment]
I would prefer ```pkgutils```

also while already hijacking this PR ^^ - how compatible to older Django version do we need to keep Jane? If time allows I would update Jane's core to django 1.11 as soon as possible ...

**Comment by krischer** [comment]
> also while already hijacking this PR ^^ - how compatible to older Django version do we need to keep Jane? If time allows I would update Jane's core to django 1.11 as soon as possible ...

Not at all I think. Only supporting the latest django + python + obspy + X versions should be perfectly fine!

**Comment by megies** [comment]
> maybe I don't see the point but why do we need this dependencies which is not working with the default installation - does the test suite in CI not work without?

This PR doesn't add any dependencies at all. I agree, the less dependencies the better. This PR simply enables using `pytest` as a drop in locally for running tests. Also this replaces the other PR about `nose`, so no need to worry.



> Not at all I think. Only supporting the latest django + python + obspy + X versions should be perfectly fine!

My only concern is about maintaining existing production servers. I don't know enough about all the migration stuff and I think the docs so far don't cover updating, really. That aside, sure, using newer versions seems like a good idea, if updating is well documented.

---

Regarding the plugin stuff: Anything's fine with me, as long as I'm able to use multiple plugins for one document type (see https://github.com/krischer/django-plugins/pull/11), this is kind of vital for my use cases.

**Comment by megies** [comment]
Thanks for merging, this helps debugging test fails locally..

**Pull request merged**
